# --- !Ups

ALTER TABLE BLOCKCHAIN_TRANSACTION."NFTPublicListing"
    DROP COLUMN IF EXISTS "broadcasted";
ALTER TABLE BLOCKCHAIN_TRANSACTION."NFTSale"
    DROP COLUMN IF EXISTS "broadcasted";
ALTER TABLE BLOCKCHAIN_TRANSACTION."SendCoin"
    DROP COLUMN IF EXISTS "broadcasted";


ALTER TABLE BLOCKCHAIN_TRANSACTION."NFTPublicListing"
    ADD COLUMN IF NOT EXISTS "timeoutHeight" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE BLOCKCHAIN_TRANSACTION."NFTSale"
    ADD COLUMN IF NOT EXISTS "timeoutHeight" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE BLOCKCHAIN_TRANSACTION."SendCoin"
    ADD COLUMN IF NOT EXISTS "timeoutHeight" INTEGER NOT NULL DEFAULT 0;


# --- !Downs
